import { useMemo, useState } from "react";
import { useNavigate } from "react-router";
import "~/index.scss";
import "./quote-bank-page.css";

const allQuotes = [
  { text: "\"Nobody owes you nothin’. You owe yourself.\" - Rocky Balboa", category: "motivation" },
  { text: "\"You don't have to be special, just consistent, determined, and willing to work for it.\" - Tom Brady", category: "motivation" },
  { text: "\"Do, or do not. There is no try.\" - Yoda", category: "motivation" },
  { text: "\"The only way to do great work is to love what you do.\" - Steve Jobs", category: "motivation" },
  { text: "\"Believe you can and you're halfway there.\" - Theodore Roosevelt", category: "motivation" },
  { text: "\"Don't watch the clock; do what it does. Keep going.\" - Sam Levenson", category: "motivation" },
  { text: "\"I like criticism. It makes you strong.\" - Lebron James", category: "motivation" },
  { text: "\"Don’t be afraid of failure. This is the way to succeed.\" - Lebron James", category: "motivation" },
  { text: "\"Success is not final; failure is not fatal: It is the courage to continue that counts.\" - Winston Churchill", category: "motivation" },
  { text: "\"Keep your eyes on the stars and your feet on the ground.\" - Theodore Roosevelt", category: "motivation" },
  { text: "\"Opportunity is missed by most people because it is dressed in overalls and looks like work.\" - Thomas Edison", category: "motivation" },
  { text: "\"Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness.\" - Oprah Winfrey", category: "motivation" },
  { text: "\"He who conquers himself is the mightiest warrior.\" - Confucius", category: "motivation" },
  { text: "\"Education is the most powerful weapon which you can use to change the world.\" - Nelson Mandela", category: "motivation" },
  { text: "\"Life is like riding a bicycle. To keep your balance, you must keep moving.\" - Albert Einstein", category: "motivation" },
  { text: "\"Be sure you put your feet in the right place, then stand firm.\" - Abraham Lincoln", category: "motivation" },
  { text: "\"You don’t find willpower, you create it.\" - Kobe Bryant", category: "motivation" },
  { text: "\"Discipline is doing what needs to be done, even when you don’t feel like doing it.\" - Mike Tyson", category: "motivation" },
  { text: "\"Hard work beats talent when talent doesn’t work hard.\" - Tim Notke", category: "motivation" },
  { text: "\"If you want to be great, stop asking for permission.\" - Ray Lewis", category: "motivation" },
  { text: "\"Champions keep playing until they get it right.\" - Billie Jean King", category: "motivation" },
  { text: "\"The pain you feel today will be the strength you feel tomorrow.\" - Arnold Schwarzenegger", category: "motivation" },
  { text: "\"You have to expect things of yourself before you can do them.\" - Michael Jordan", category: "motivation" },
  { text: "\"No one is going to hand you anything. You have to go out and take it.\" - Derrick Rose", category: "motivation" },
  { text: "\"Success doesn’t come from what you do occasionally, it comes from what you do consistently.\" - Marie Forleo", category: "motivation" },
  { text: "\"It’s not about being the best. It’s about being better than you were yesterday.\" - J.J. Watt", category: "motivation" },
  { text: "\"Never let the fear of striking out keep you from playing the game.\" - Babe Ruth", category: "motivation" },
  { text: "\"Pressure is a privilege.\" - Billie Jean King", category: "motivation" },
  { text: "\"Don’t count the days, make the days count.\" - Muhammad Ali", category: "motivation" },
  { text: "\"Some people want it to happen, some wish it would happen, others make it happen.\" - Michael Jordan", category: "motivation" },
  { text: "\"Excellence is not a singular act, but a habit. You are what you repeatedly do.\" - Shaquille O’Neal", category: "motivation" },
  { text: "\"Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing.\" - Pelé", category: "motivation" },
  { text: "\"Every champion was once a contender that refused to give up.\" - Rocky Balboa", category: "motivation" },
  { text: "\"The difference between the impossible and the possible lies in a person’s determination.\" - Tommy Lasorda", category: "motivation" },
  { text: "\"It’s not whether you get knocked down, it’s whether you get up.\" - Vince Lombardi", category: "motivation" },
  { text: "\"The only place success comes before work is in the dictionary.\" - Vince Lombardi", category: "motivation" },
  { text: "\"Winning takes talent, to repeat takes character.\" - John Wooden", category: "motivation" },
  { text: "\"Don’t measure yourself by what you have accomplished, but by what you should have accomplished with your ability.\" - John Wooden", category: "motivation" },
  { text: "\"I’ve failed over and over and over again in my life. And that is why I succeed.\" - Michael Jordan", category: "motivation" },
  { text: "\"Greatness is not guarding yourself from the people; greatness is being accepted by the people.\" - Mike Tyson", category: "motivation" },
  { text: "\"When you’re good at something, you’ll tell everyone. When you’re great at something, they’ll tell you.\" - Walter Payton", category: "motivation" },
  { text: "\"I hated every minute of training, but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion.’\" - Muhammad Ali", category: "motivation" },
  { text: "\"Push yourself again and again. Don’t give an inch until the final buzzer sounds.\" - Larry Bird", category: "motivation" },
  { text: "\"Success is achieved by developing our strengths, not by eliminating our weaknesses.\" - Marilyn vos Savant", category: "motivation" },
  { text: "\"There may be people that have more talent than you, but there’s no excuse for anyone to work harder than you do.\" - Derek Jeter", category: "motivation" },
  { text: "\"Confidence comes from preparation. Everything else is beyond your control.\" - Peyton Manning", category: "motivation" },
  { text: "\"Do not let what you cannot do interfere with what you can do.\" - John Wooden", category: "motivation" },
  { text: "\"Always turn a negative situation into a positive one.\" - Michael Jordan", category: "motivation" },
  { text: "\"Talent is God-given. Be humble. Fame is man-given. Be grateful. Conceit is self-given. Be careful.\" - John Wooden", category: "motivation" },
  { text: "\"Success usually comes to those who are too busy to be looking for it.\" - Henry David Thoreau", category: "motivation" },
  { text: "\"Strive not to be a success, but rather to be of value.\" - Albert Einstein", category: "motivation" },
  { text: "\"Whether you think you can or you think you can’t, you’re right.\" - Henry Ford", category: "motivation" },
  { text: "\"If you’re going through hell, keep going.\" - Winston Churchill", category: "motivation" },
  { text: "\"Act as if what you do makes a difference. It does.\" - William James", category: "motivation" },
  { text: "\"Success is getting what you want. Happiness is wanting what you get.\" - Dale Carnegie", category: "motivation" },
  { text: "\"Don’t wait. The time will never be just right.\" - Napoleon Hill", category: "motivation" },
  { text: "\"It does not matter how slowly you go as long as you do not stop.\" - Confucius", category: "motivation" },
  { text: "\"You have power over your mind—not outside events. Realize this, and you will find strength.\" - Marcus Aurelius", category: "motivation" },
  { text: "\"Be yourself; everyone else is already taken.\" - Oscar Wilde", category: "motivation" },
  { text: "\"If you want to lift yourself up, lift up someone else.\" - Booker T. Washington", category: "motivation" },
  { text: "\"The best way to predict the future is to create it.\" - Peter Drucker", category: "motivation" },
  { text: "\"The only limit to our realization of tomorrow is our doubts of today.\" - Franklin D. Roosevelt", category: "motivation" },
  { text: "\"What lies behind us and what lies before us are tiny matters compared to what lies within us.\" - Ralph Waldo Emerson", category: "motivation" },
  { text: "\"I am not a product of my circumstances. I am a product of my decisions.\" - Stephen Covey", category: "motivation" },
  { text: "\"The future belongs to those who believe in the beauty of their dreams.\" - Eleanor Roosevelt", category: "motivation" },
  { text: "\"Start where you are. Use what you have. Do what you can.\" - Arthur Ashe", category: "motivation" },
  { text: "\"Do one thing every day that scares you.\" - Eleanor Roosevelt", category: "motivation" },
  { text: "\"Success is liking yourself, liking what you do, and liking how you do it.\" - Maya Angelou", category: "motivation" },
  { text: "\"The way to get started is to quit talking and begin doing.\" - Walt Disney", category: "motivation" },
  { text: "\"Dream big and dare to fail.\" - Norman Vaughan", category: "motivation" },
  { text: "\"Success is how high you bounce when you hit bottom.\" - George S. Patton", category: "motivation" },
  { text: "\"Energy and persistence conquer all things.\" - Benjamin Franklin", category: "motivation" },
  { text: "\"Work like hell. I mean you just have to put in 80 to 100 hour weeks every week.\" - Elon Musk", category: "motivation" },
  { text: "\"If something is important enough, even if the odds are against you, you should still do it.\" - Elon Musk", category: "motivation" },
  { text: "\"Innovation distinguishes between a leader and a follower.\" - Steve Jobs", category: "motivation" },
  { text: "\"Stay hungry. Stay foolish.\" - Steve Jobs", category: "motivation" },
  { text: "\"Your time is limited, so don’t waste it living someone else’s life.\" - Steve Jobs", category: "motivation" },
  { text: "\"Logic will get you from A to B. Imagination will take you everywhere.\" - Albert Einstein", category: "motivation" },
  { text: "\"It always seems impossible until it’s done.\" - Nelson Mandela", category: "motivation" },
  { text: "\"We must use time wisely and forever realize that the time is always ripe to do right.\" - Nelson Mandela", category: "motivation" },
  { text: "\"What you do makes a difference, and you have to decide what kind of difference you want to make.\" - Jane Goodall", category: "motivation" },
  { text: "\"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.\" - Christian D. Larson", category: "motivation" },
  { text: "\"Success is the sum of small efforts, repeated day in and day out.\" - Robert Collier", category: "motivation" },
  { text: "\"What you get by achieving your goals is not as important as what you become by achieving your goals.\" - Zig Ziglar", category: "motivation" },
  { text: "\"Perseverance is not a long race; it is many short races one after another.\" - Walter Elliot", category: "motivation" },
  { text: "\"Limit your ‘always’ and your ‘nevers.’\" - Amy Poehler", category: "motivation" },
  { text: "\"Success is not how high you have climbed, but how you make a positive difference to the world.\" - Roy T. Bennett", category: "motivation" },
  { text: "\"Opportunity is everywhere. The key is to develop the vision to see it.\" - Robin Sharma", category: "motivation" },
  { text: "\"You can't cross the sea merely by standing and staring at the water.\" - Rabindranath Tagore", category: "motivation" },
  { text: "\"If opportunity doesn’t knock, build a door.\" - Milton Berle", category: "motivation" },
  { text: "\"Don’t limit yourself. Many people limit themselves to what they think they can do.\" - Mary Kay Ash", category: "motivation" },
  { text: "\"Be so good they can’t ignore you.\" - Steve Martin", category: "motivation" },
  { text: "\"The most difficult thing is the decision to act, the rest is merely tenacity.\" - Amelia Earhart", category: "motivation" },
  { text: "\"You miss 100% of the shots you don’t take.\" - Wayne Gretzky", category: "motivation" },
  { text: "\"Do not go where the path may lead, go instead where there is no path and leave a trail.\" - Ralph Waldo Emerson", category: "motivation" },
  { text: "\"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.\" - Roy T. Bennett", category: "motivation" },
  { text: "\"Only those who dare to fail greatly can ever achieve greatly.\" - Robert F. Kennedy", category: "motivation" },
  { text: "\"Success means doing the best we can with what we have.\" - Zig Ziglar", category: "motivation" },
  { text: "\"Never bend your head. Always hold it high. Look the world straight in the eye.\" - Helen Keller", category: "motivation" },
  { text: "\"If you want something you've never had, you must be willing to do something you've never done.\" - Thomas Jefferson", category: "motivation" },
  { text: "\"No one ever told me that grief felt so like fear.\" - C.S. Lewis", category: "loss" },
  { text: "\"The reality is that you will grieve forever. You will not ‘get over’ the loss of a loved one; you will learn to live with it.\" - Elisabeth Kubler-Ross", category: "loss" },
  { text: "\"You may not control all the events that happen to you, but you can decide not to be reduced by them.\" - Maya Angelou", category: "loss" },
  { text: "\"You will lose someone you can’t live without, and your heart will be badly broken... But the truth is that grief is like the ocean; it comes on waves, ebbing and flowing.\" - Anne Lamott", category: "loss" },
  { text: "\"The deeper that sorrow carves into your being, the more joy you can contain.\" - Khalil Gibran", category: "loss" },
  { text: "\"Grief turns out to be a place none of us know until we reach it.\" - Joan Didion", category: "loss" },
  { text: "\"Grief is the price we pay for love.\" - Queen Elizabeth II", category: "loss" },
  { text: "\"Grief and resilience live together.\" - Michelle Obama", category: "loss" },
  { text: "\"The pain of loss is a reminder that we have loved deeply. And the depth of that love can inspire us to be better, kinder, more courageous people.\" - Barack Obama", category: "loss" },
  { text: "\"Anything that's human is mentionable, and anything that is mentionable can be more manageable.\" - Mr. Rogers", category: "loss" },
  { text: "\"Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.\" - Steve Jobs", category: "loss" },
  { text: "\"Only when we are brave enough to explore the darkness will we discover the infinite power of our light.\" - Brene Brown", category: "loss" },
  { text: "\"The greatest glory in living lies not in never falling, but in rising every time we fall.\" - Nelson Mandela", category: "loss" },
  { text: "\"You never know how strong you are until being strong is your only choice.\" - Bob Marley", category: "loss" },
  { text: "\"Turn your wounds into wisdom.\" - Oprah Winfrey", category: "loss" },
  { text: "\"We must accept finite disappointment, but never lose infinite hope.\" - Martin Luther King Jr.", category: "loss" },
  { text: "\"What we have once enjoyed we can never lose. All that we love deeply becomes a part of us.\" - Helen Keller", category: "loss" },
  { text: "\"The best way to not feel hopeless is to get up and do something.\" - Barack Obama", category: "loss" },
  { text: "\"When we are no longer able to change a situation, we are challenged to change ourselves.\" - Viktor Frankl", category: "loss" },
  { text: "\"Helping people in need is a good and essential part of my life, a kind of destiny.\" - Princess Diana", category: "loss" },
  { text: "\"The world breaks everyone, and afterward, many are strong at the broken places.\" - Ernest Hemingway", category: "loss" },
  { text: "\"If you’re going through hell, keep going.\" - Winston Churchill", category: "loss" },
  { text: "\"Don’t grieve. Anything you lose comes round in another form.\" - Rumi", category: "loss" },
  { text: "\"Our greatest glory is not in never falling, but in rising every time we fall.\" - Confucius", category: "loss" },
  { text: "\"There is a crack in everything, that’s how the light gets in.\" - Leonard Cohen", category: "loss" },
  { text: "\"Tears shed for another person are not a sign of weakness. They are a sign of a pure heart.\" - José N. Harris", category: "loss" },
  { text: "\"Sadness flies away on the wings of time.\" - Jean de La Fontaine", category: "loss" },
  { text: "\"Grief is in two parts. The first is loss. The second is the remaking of life.\" - Anne Roiphe", category: "loss" },
  { text: "\"How lucky I am to have something that makes saying goodbye so hard.\" - A.A. Milne", category: "loss" },
  { text: "\"To weep is to make less the depth of grief.\" - William Shakespeare", category: "loss" },
  { text: "\"Sometimes even to live is an act of courage.\" - Seneca", category: "loss" },
  { text: "\"Out of suffering have emerged the strongest souls.\" - Khalil Gibran", category: "loss" },
  { text: "\"Do not cry because they are gone. Smile because they lived.\" - Dr. Seuss", category: "loss" },
  { text: "\"Healing doesn’t mean the damage never existed. It means the damage no longer controls our lives.\" - Akshay Dubey", category: "loss" },
  { text: "\"Grief does not change you. It reveals you.\" - John Green", category: "loss" },
  { text: "\"You cannot protect yourself from sadness without protecting yourself from happiness.\" - Jonathan Safran Foer", category: "loss" },
  { text: "\"There is something beautiful about all scars, whatever nature. A scar means the hurt is over.\" - Harry Crews", category: "loss" },
  { text: "\"Hope is being able to see that there is light despite all of the darkness.\" - Desmond Tutu", category: "loss" },
  { text: "\"Every man's memory is his private literature.\" - Aldous Huxley", category: "loss" },
  { text: "\"We bereaved are not alone. We belong to the largest company in all the world—the company of those who have known suffering.\" - Helen Keller", category: "loss" },
  { text: "\"The pain passes, but the beauty remains.\" - Pierre Auguste Renoir", category: "loss" },
  { text: "\"Loss is nothing else but change, and change is Nature’s delight.\" - Marcus Aurelius", category: "loss" },
  { text: "\"Give sorrow words; the grief that does not speak knits up the o’er-wrought heart and bids it break.\" - William Shakespeare", category: "loss" },
  { text: "\"When someone you love becomes a memory, that memory becomes a treasure.\" - Unknown", category: "loss" },
  { text: "\"The song is ended, but the melody lingers on.\" - Irving Berlin", category: "loss" },
  { text: "\"Grief is love with nowhere to go.\" - Jamie Anderson", category: "loss" },
  { text: "\"Life is full of grief, to exactly the degree we allow ourselves to love other people.\" - Orson Scott Card", category: "loss" },
  { text: "\"People touch our lives if only for a moment, and yet we’re not the same from that moment on.\" - Unknown", category: "loss" },
  { text: "\"Death ends a life, not a relationship.\" - Mitch Albom", category: "loss" },
  { text: "\"Nothing that grieves us can be called little; by the eternal laws of proportion a child’s loss of a doll and a king’s loss of a crown are events of the same size.\" - Mark Twain", category: "loss" },
  { text: "\"To live in hearts we leave behind is not to die.\" - Thomas Campbell", category: "loss" },
  { text: "\"Sometimes the smallest things take up the most room in your heart.\" - A.A. Milne", category: "loss" },
  { text: "\"Say not in grief ‘he is no more,’ but live in thankfulness that he was.\" - Hebrew Proverb", category: "loss" },
  { text: "\"When we lose someone we love, we must learn not to live without them, but to live with the love they left behind.\" - Unknown", category: "loss" },
  { text: "\"Death leaves a heartache no one can heal, love leaves a memory no one can steal.\" - Irish Proverb", category: "loss" },
  { text: "\"The reality is that you will grieve forever. You will not ‘get over’ the loss... you will be healed and you will rebuild yourself around the loss you have suffered.\" - Unknown", category: "loss" },
  { text: "\"Grief is not a disorder, a disease or a sign of weakness. It is an emotional, physical and spiritual necessity.\" - Earl Grollman", category: "loss" },
  { text: "\"Sometimes we just need someone to simply be there — not to fix anything, but to let us feel we are supported and not alone.\" - Unknown", category: "loss" },
  { text: "\"Those we love and lose are always connected by heartstrings into infinity.\" - Terri Guillemets", category: "loss" },
  { text: "\"Say goodbye to the past, but never forget it — it made you who you are.\" - Unknown", category: "loss" },
  { text: "\"You don’t get over it, you just get through it. You don’t get by it, because you can’t get around it. It doesn’t ‘get better,’ it just gets different.\" - Wendy Feireisen", category: "loss" },
  { text: "\"There are no happy endings. Endings are the saddest part, so just give me a happy middle and a very happy start.\" - Shel Silverstein", category: "loss" },
  { text: "\"You will survive and you will find purpose in the chaos. Moving on doesn’t mean letting go.\" - Mary VanHaute", category: "loss" },
  { text: "\"Grief is not a sign of weakness, nor a lack of faith. It is the price of love.\" - Unknown", category: "loss" },
  { text: "\"You don’t go around grieving all the time, but the grief is still there and always will be.\" - Nigella Lawson", category: "loss" },
  { text: "\"Where there is deep grief, there was great love.\" - Unknown", category: "loss" },
  { text: "\"When the heart grieves over what it has lost, the spirit rejoices over what it has left.\" - Sufi Proverb", category: "loss" },
  { text: "\"Grief is like glitter. You can throw a handful of it into the air, but when you try to clean it up, you’ll never get it all. Even long after the event, you’ll still find glitter tucked into corners.\" - Elaine Davis", category: "loss" },
  { text: "\"Time does not heal all wounds. It just gives us the tools to endure them.\" - Unknown", category: "loss" },
  { text: "\"We do not ‘move on’ from grief. We move forward with it.\" - Nora McInerny", category: "loss" },
  { text: "\"Grief is simply love with no place to go.\" - Unknown", category: "loss" },
  { text: "\"In the process of letting go, you will lose many things from the past, but you will find yourself.\" - Deepak Chopra", category: "loss" },
  { text: "\"Death is not the opposite of life, but a part of it.\" - Haruki Murakami", category: "loss" },
  { text: "\"When someone you love dies, you never quite get over it. You just slowly learn how to go on without them, always keeping them tucked safely in your heart.\" - Unknown", category: "loss" },
  { text: "\"The risk of love is loss, and the price of loss is grief. But the pain of grief is only a shadow when compared with the pain of never risking love.\" - Hilary Stanton Zunin", category: "loss" },
  { text: "\"Sometimes grief is like a raging river; other times, it's a quiet ache. But it is always love trying to find a place to land.\" - Unknown", category: "loss" },
  { text: "\"No rule book. No time frame. No judgment. Grieve how you need to.\" - Unknown", category: "loss" },
  { text: "\"There is no right way to grieve; there is only your way.\" - Unknown", category: "loss" },
  { text: "\"Each person's grief is as unique as their fingerprint.\" - David Kessler", category: "loss" },
  { text: "\"The cure for anything is salt water: sweat, tears or the sea.\" - Isak Dinesen", category: "loss" },
  { text: "\"Life has to end. Love doesn’t.\" - Mitch Albom", category: "loss" },
  { text: "\"To mourn is to touch directly the substance of divine compassion.\" - Stephen Levine", category: "loss" },
  { text: "\"Grief, after all, is the price we pay for being brave enough to love.\" - Amanda Gorman", category: "loss" },
  { text: "\"You care so much you feel as though you will bleed to death with the pain of it.\" - J.K. Rowling", category: "loss" },
  { text: "\"There is no grief like the grief that does not speak.\" - Henry Wadsworth Longfellow", category: "loss" },
  { text: "\"The reality is that you will grieve forever... You will never be the same again. Nor should you be.\" - Alan D. Wolfelt", category: "loss" },
  { text: "\"When you lose someone you love, you gain an angel you know.\" - Unknown", category: "loss" },
  { text: "\"To live in the hearts of those we love is never to die.\" - Hazel Gaynor", category: "loss" },
  { text: "\"Each day is a step toward healing. Some days are just bigger steps than others.\" - Unknown", category: "loss" },
  { text: "\"When you are sorrowful look again in your heart, and you shall see that in truth you are weeping for that which has been your delight.\" - Kahlil Gibran", category: "loss" },
  { text: "\"Grief is the agony of an instant; the indulgence of grief the blunder of a life.\" - Benjamin Disraeli", category: "loss" },
  { text: "\"No one is actually dead until the ripples they cause in the world die away.\" - Terry Pratchett", category: "loss" },
  { text: "\"There is something in the human spirit that will survive and prevail. There is a tiny and brilliant light burning in the heart of man that will not go out no matter how dark the world becomes.\" - Leo Tolstoy", category: "loss" },
  { text: "\"We never truly get over a loss, but we can move forward and evolve from it.\" - Elizabeth Berrien", category: "loss" },
  { text: "\"Love knows not its own depth until the hour of separation.\" - Kahlil Gibran", category: "loss" },
  { text: "\"You’ll get through this. It will hurt, but you’ll come out stronger on the other side. Different, but stronger.\" - Unknown", category: "loss" },
  { text: "\"Even the strongest feelings expire when ignored and taken for granted, but grief is not one of them.\" - Nitya Prakash", category: "loss" },
  { text: "\"Grief is like the wind. You can’t see it, but you can feel it in every bone.\" - Unknown", category: "loss" },
  { text: "\"Sorrow can be alleviated by good sleep, a bath, and a glass of wine.\" - Thomas Aquinas", category: "loss" },
  { text: "\"There are moments that mark your life. Moments when you realize nothing will ever be the same, and time is divided into two parts: before this and after this.\" - Unknown", category: "loss" },
  { text: "\"Acceptance of oneself is the essence of the experience of life.\" – James Baldwin", category: "acceptance" },
  { text: "\"The first step toward change is awareness. The second step is acceptance.\" – Nathaniel Branden", category: "acceptance" },
  { text: "\"What you think of yourself is much more important than what people think of you.\" – Lucille Ball", category: "acceptance" },
  { text: "\"Once we accept our limits, we go beyond them.\" – Albert Einstein", category: "acceptance" },
  { text: "\"Acceptance is the key to unlocking the doors of peace.\" – Sharon Salzberg", category: "acceptance" },
  { text: "\"Acceptance doesn’t mean resignation; it means understanding that something is what it is.\" – Michael J. Fox", category: "acceptance" },
  { text: "\"We cannot change what we are not willing to confront.\" – James Baldwin", category: "acceptance" },
  { text: "\"The more we learn to accept ourselves, the more we can accept others.\" – Eckhart Tolle", category: "acceptance" },
  { text: "\"Life is about accepting the challenges along the way, choosing to keep moving forward, and savoring the journey.\" – Roy T. Bennett", category: "acceptance" },
  { text: "\"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.\" – Ralph Waldo Emerson", category: "acceptance" },
  { text: "\"Life isn’t about finding yourself. Life is about creating yourself.\" – George Bernard Shaw", category: "acceptance" },
  { text: "\"It’s not what happens to you, but how you react to it that matters.\" – Epictetus", category: "acceptance" },
  { text: "\"You have to be able to accept failure to get better.\" – Lewis Hamilton", category: "acceptance" },
  { text: "\"To love oneself is the beginning of a lifelong romance.\" – Oscar Wilde", category: "acceptance" },
  { text: "\"You must do the things you think you cannot do.\" – Eleanor Roosevelt", category: "acceptance" },
  { text: "\"Peace is not the absence of conflict, but the ability to cope with it.\" – Dorothy Thompson", category: "acceptance" },
  { text: "\"Acceptance of what has happened is the first step to overcoming the consequences of any misfortune.\" – William James", category: "acceptance" },
  { text: "\"Be yourself; everyone else is already taken.\" – Oscar Wilde", category: "acceptance" },
  { text: "\"The greatest way to heal is to accept your past and move on.\" – Unknown", category: "acceptance" },
  { text: "\"Acceptance is the key to finding peace. Resting and letting go of the things we cannot change makes room for growth.\" – Samantha S. Smith", category: "acceptance" },
  { text: "\"Peace comes from within. Do not seek it without.\" – Buddha", category: "acceptance" },
  { text: "\"What you resist not only persists, but it also grows stronger.\" – Carl Jung", category: "acceptance" },
  { text: "\"The best way to make peace with yourself is to accept yourself fully.\" – Maxime Lagacé", category: "acceptance" },
  { text: "\"Happiness can exist only in acceptance.\" – George Orwell", category: "acceptance" },
  { text: "\"Every day is a new beginning. Take a deep breath, smile, and start again.\" – Unknown", category: "acceptance" },
  { text: "\"I am not what happened to me, I am what I choose to become.\" – Carl Jung", category: "acceptance" },
  { text: "\"You have to accept whatever comes, and … meet it with the best you have to give.\" – Eleanor Roosevelt", category: "acceptance" },
  { text: "\"The more anger we hold onto, the less we can love ourselves or others. Acceptance helps to lay that burden down.\" – Maya Angelou", category: "acceptance" },
  { text: "\"It’s through…grieving that acceptance arrives.\" – Sheryl Paul", category: "acceptance" },
  { text: "\"Acceptance is the art of making someone who has just done you a small favor wish that he might have done you a greater one.\" – Martin Luther King Jr.", category: "acceptance" },
  { text: "\"Life is a series of natural and spontaneous changes. Don’t resist them; that only creates sorrow.\" – Lao Tzu", category: "acceptance" },
  { text: "\"My happiness grows in direct proportion to my acceptance, and in inverse proportion to my expectations.\" – Michael J. Fox", category: "acceptance" },
  { text: "\"For after all, the best thing one can do when it is raining is let it rain.\" – Henry Wadsworth Longfellow", category: "acceptance" },
  { text: "\"The only way to make sense out of change is to plunge into it, move with it, and join the dance.\" – Alan Watts", category: "acceptance" },
  { text: "\"We must accept finite disappointment, but never lose infinite hope.\" – Martin Luther King Jr.", category: "acceptance" },
  { text: "\"To be beautiful means to be yourself. You don’t need to be accepted by others. You need to accept yourself.\" – Thích Nhất Hạnh", category: "acceptance" },
  { text: "\"And I think … sometimes the only choice is between acceptance and madness.\" – Cassandra Clare", category: "acceptance" },
  { text: "\"The boundary to what we can accept is the boundary to our freedom.\" – Tara Brach", category: "acceptance" },
  { text: "\"God, grant me the serenity to accept the things I cannot change…\" – Reinhold Niebuhr", category: "acceptance" },
  { text: "\"Radical Acceptance is the art of engaging fully in this world.\" – Tara Brach", category: "acceptance" },
  { text: "\"To be human is to grow toward an acceptance of paradox.\" – Sheryl Paul", category: "acceptance" },
  { text: "\"We must accept life for what it actually is.\" – Ida Wylie", category: "acceptance" },
  { text: "\"Acceptance involves the action of allowing the presence of all experiences.\" – Jill Stoddard", category: "acceptance" },
  { text: "\"Acceptance opens the door for growth and transformation.\" – Eckhart Tolle", category: "acceptance" },
  { text: "\"Accepting the reality of the present moment allows us to move forward with clarity and purpose.\" – Deepak Chopra", category: "acceptance" },
  { text: "\"Accepting your own worth leads to liberation from self-doubt.\" – Louise Hay", category: "acceptance" },
  { text: "\"Acceptance is not passivity; it is the foundation for positive change.\" – Dalai Lama", category: "acceptance" },
  { text: "\"Acceptance fosters empathy and creates bridges of understanding.\" – Thích Nhất Hạnh", category: "acceptance" },
  { text: "\"Acceptance liberates us from the burden of judgment.\" – Marianne Williamson", category: "acceptance" },
  { text: "\"Accept – then act. Whatever the present moment contains, accept it as if you had chosen it.\" – Eckhart Tolle", category: "acceptance" },
  { text: "\"What self-acceptance does is open up more possibilities for success.\" – Shannon Ables", category: "acceptance" },
  { text: "\"The way of love is not a subtle argument. It is total acceptance.\" – Osho", category: "acceptance" },
  { text: "\"Acceptance is the road to all change.\" – Bryant H. McGill", category: "acceptance" },
  { text: "\"Time does not heal everything but acceptance will heal everything.\" – Unknown", category: "acceptance" },
  { text: "\"The only person we have the right or power to forgive is ourselves.\" – Rebecca O’Dwyer", category: "acceptance" },
  { text: "\"Being authentic begins with unconditional self-acceptance.\" – Azim Jamal", category: "acceptance" },
  { text: "\"Life is 10% what happens to us and 90% how we react to it.\" – Charles R. Swindoll", category: "acceptance" },
  { text: "\"The art of life lies in a constant readjustment to our surroundings.\" – Kakuzo Okakura", category: "acceptance" },
  { text: "\"Bend like the willow, for if you resist, the storm will break you.\" – Proverb", category: "acceptance" },
  { text: "\"Life is a shipwreck, but we must not forget to sing in the lifeboats.\" – Voltaire", category: "acceptance" },
  { text: "\"The only thing that is constant is change.\" – Heraclitus", category: "acceptance" },
  { text: "\"When we can no longer change a situation, we are challenged to change ourselves.\" – Viktor Frankl", category: "acceptance" },
  { text: "\"Accepting oneself does not preclude an attempt to become better.\" – Flannery O’Connor", category: "acceptance" },
  { text: "\"Whatever the present moment contains, accept it as if you had chosen it.\" – Eckhart Tolle", category: "acceptance" },
  { text: "\"Face your life, its pain, its pleasure, leave no path untaken.\" – Neil Gaiman", category: "acceptance" },
  { text: "\"What you deny submits you. What you accept transforms you.\" – Carl Jung", category: "acceptance" },
  { text: "\"Embrace uncertainty. Some of the most beautiful chapters in our lives won’t have a title until much later.\" – Bob Goff", category: "acceptance" },
  { text: "\"Life goes on, and so must we.\" – Stephen King", category: "acceptance" },
  { text: "\"Accept challenges, so that you may feel the exhilaration of victory.\" – George S. Patton", category: "acceptance" },
  { text: "\"The greatest discovery of all time is that a person can change their future by merely changing their attitude.\" – Oprah Winfrey", category: "acceptance" },
  { text: "\"Our ability to adapt is amazing. Our ability to change isn’t as spectacular.\" – Lisa Lutz", category: "acceptance" },
  { text: "\"Tough times don’t last, tough people do.\" – Robert H. Schuller", category: "acceptance" },
  { text: "\"The only way out is through.\" – Robert Frost", category: "acceptance" },
  { text: "\"It’s not the load that breaks you down, it’s the way you carry it.\" – Lou Holtz", category: "acceptance" },
  { text: "\"There is no love without forgiveness, and there is no forgiveness without love.\" – Bryant H. McGill", category: "acceptance" },
  { text: "\"Change what you can, manage what you can’t.\" – Raymond McCauley", category: "acceptance" },
  { text: "\"You are braver than you believe, stronger than you seem, and smarter than you think.\" – A.A. Milne", category: "acceptance" },
  { text: "\"Hard times may have held you down, but they will not last forever.\" – Mike Ditka", category: "acceptance" },
  { text: "\"Nothing diminishes anxiety faster than action.\" – Walter Anderson", category: "acceptance" },
  { text: "\"When adversity strikes, that’s when you have to be the most calm. Take a step back, stay strong, stay grounded and press on.\" – LL Cool J", category: "acceptance" },
  { text: "\"Adversity has the effect of eliciting talents which in prosperous circumstances would have lain dormant.\" – Horace", category: "acceptance" },
  { text: "\"We don’t develop courage by being happy every day. We develop it by surviving difficult times and challenging adversity.\" – Barbara De Angelis", category: "acceptance" },
  { text: "\"Acceptance of what has happened is the first step to overcoming the consequences of any misfortune.\" – William James", category: "acceptance" },
  { text: "\"We cannot change the cards we are dealt, just how we play the hand.\" – Randy Pausch", category: "acceptance" },
  { text: "\"Amor fati: Love your fate, which is in fact your life.\" – Friedrich Nietzsche", category: "acceptance" },
  { text: "\"Let us accept truth, even when it surprises us and alters our views.\" – George Sand", category: "acceptance" },
  { text: "\"Do not waste your energy fighting the inevitable. Instead, learn to flow with it.\" – Tony Robbins", category: "acceptance" },
  { text: "\"The moment you accept yourself, you become beautiful.\" – Osho", category: "acceptance" },
  { text: "\"Everything that irritates us about others can lead us to an understanding of ourselves.\" – Carl Jung", category: "acceptance" },
  { text: "\"True compassion is not just about giving, but accepting others as they are.\" – Dalai Lama", category: "acceptance" },
  { text: "\"Know that everything is in perfect order whether you understand it or not.\" – Valery Satterwhite", category: "acceptance" },
  { text: "\"Freedom is not worth having if it does not include the freedom to make mistakes.\" – Mahatma Gandhi", category: "acceptance" },
  { text: "\"Be willing to have it so. Acceptance of what has happened is the first step to overcoming the consequences of any misfortune.\" – William James", category: "acceptance" },
  { text: "\"The curious paradox is that when I accept myself just as I am, then I can change.\" – Carl Rogers", category: "acceptance" },
  { text: "\"Acceptance doesn’t mean you have to like it. It just means you stop trying to control it.\" – Lori Deschene", category: "acceptance" },
  { text: "\"You can't stop the waves, but you can learn to surf.\" – Jon Kabat-Zinn", category: "acceptance" },
  { text: "\"Acceptance is simply love in practice.\" – Tara Brach", category: "acceptance" },
  { text: "\"Sometimes you just have to accept that some people can stay in your heart but not in your life.\" – Unknown", category: "acceptance" },
  { text: "\"Maturity is learning to walk away from people and situations that threaten your peace of mind.\" – Unknown", category: "acceptance" },
  { text: "\"The secret to happiness is letting every situation be what it is instead of what you think it should be.\" – Mandy Hale", category: "acceptance" },
  { text: "\"Loneliness expresses the pain of being alone and solitude expresses the glory of being alone.\" – Paul Tillich", category: "loneliness" },
  { text: "\"The eternal quest of the human being is to shatter his loneliness.\" – Norman Cousins", category: "loneliness" },
  { text: "\"The greatest thing in the world is to know how to belong to oneself.\" – Michel de Montaigne", category: "loneliness" },
  { text: "\"The worst loneliness is not to be comfortable with yourself.\" – Mark Twain", category: "loneliness" },
  { text: "\"Loneliness and the feeling of being unwanted is the most terrible poverty.\" – Mother Teresa", category: "loneliness" },
  { text: "\"I used to think the worst thing in life was to end up all alone. It’s not. The worst thing in life is ending up with people who make you feel alone.\" – Robin Williams", category: "loneliness" },
  { text: "\"If you are lonely when you’re alone, you are in bad company.\" – Jean-Paul Sartre", category: "loneliness" },
  { text: "\"Loneliness adds beauty to life. It puts a special burn on sunsets and makes night air smell better.\" – Henry Rollins", category: "loneliness" },
  { text: "\"Inside myself is a place where I live all alone and that’s where you renew your springs that never dry up.\" – Pearl S. Buck", category: "loneliness" },
  { text: "\"Pray that your loneliness may spur you into finding something to live for, great enough to die for.\" – Dag Hammarskjöld", category: "loneliness" },
  { text: "\"Music was my refuge. I could crawl into the space between the notes and curl my back to loneliness.\" – Maya Angelou", category: "loneliness" },
  { text: "\"We are all so much together, but we are all dying of loneliness.\" – Albert Schweitzer", category: "loneliness" },
  { text: "\"Loneliness is the human condition. Cultivate it. The way it tunnels into you allows your soul room to grow.\" – Janet Fitch", category: "loneliness" },
  { text: "\"There’s a loneliness that only exists in someone’s mind. The loneliest place to be is in your own head.\" – Unknown", category: "loneliness" },
  { text: "\"People think being alone makes you lonely, but I don’t think that’s true. Being surrounded by the wrong people is the loneliest thing in the world.\" – Kim Culbertson", category: "loneliness" },
  { text: "\"Sometimes you need to be alone. Not to be lonely, but to enjoy your free time being yourself.\" – Unknown", category: "loneliness" },
  { text: "\"The soul that sees beauty may sometimes walk alone.\" – Johann Wolfgang von Goethe", category: "loneliness" },
  { text: "\"It’s easy to stand with the crowd. It takes courage to stand alone.\" – Mahatma Gandhi", category: "loneliness" },
  { text: "\"Loneliness is not a lack of company, it’s a lack of purpose.\" – Guillermo Maldonado", category: "loneliness" },
  { text: "\"Being alone has a power that very few people can handle.\" – Steven Aitchison", category: "loneliness" },
  { text: "\"Solitude is fine but you need someone to tell that solitude is fine.\" – Honoré de Balzac", category: "loneliness" },
  { text: "\"Sometimes I just want someone to hug me and say, ‘I know it’s hard. You’re going to be okay.’\" – Unknown", category: "loneliness" },
  { text: "\"Loneliness is a sign you are in desperate need of yourself.\" – Rupi Kaur", category: "loneliness" },
  { text: "\"Loneliness doesn’t come from being alone. It comes from feeling like no one cares.\" – Unknown", category: "loneliness" },
  { text: "\"Sometimes, you just need a break. In a beautiful place. Alone. To figure everything out.\" – Unknown", category: "loneliness" },
  { text: "\"There is no greater sorrow than to recall in misery the time when we were happy.\" – Dante Alighieri", category: "loneliness" },
  { text: "\"Absence makes the heart grow fonder, but it sure makes the rest of you lonely.\" – Charles M. Schulz", category: "loneliness" },
  { text: "\"You cannot be lonely if you like the person you’re alone with.\" – Wayne Dyer", category: "loneliness" },
  { text: "\"Loneliness is like a long rainy afternoon.\" – Haruki Murakami", category: "loneliness" },
  { text: "\"To be alone is to be different, to be different is to be alone.\" – Suzanne Gordon", category: "loneliness" },
  { text: "\"Loneliness is not being alone; it’s loving others to no avail.\" – John Berendt", category: "loneliness" },
  { text: "\"Loneliness is the poverty of self; solitude is the richness of self.\" – May Sarton", category: "loneliness" },
  { text: "\"Alone had always felt like an actual place to me.\" – Cheryl Strayed", category: "loneliness" },
  { text: "\"Nothing makes us so lonely as our secrets.\" – Paul Tournier", category: "loneliness" },
  { text: "\"I’m not much but I’m all I have.\" – Philip K. Dick", category: "loneliness" },
  { text: "\"The strongest men are the most alone.\" – Henrik Ibsen", category: "loneliness" },
  { text: "\"Loneliness is the first thing which God’s eye named not good.\" – John Milton", category: "loneliness" },
  { text: "\"Being alone feels like dying without the relief of death.\" – Unknown", category: "loneliness" },
  { text: "\"Sometimes I feel so lonely in this world, like I don’t belong anywhere or to anyone.\" – Unknown", category: "loneliness" },
  { text: "\"You are never alone. You are eternally connected with everyone.\" – Amit Ray", category: "loneliness" },
  { text: "\"Loneliness is a bridge between who you are and who you’re becoming.\" – Brianna Wiest", category: "loneliness" },
  { text: "\"Lonely is not being alone, it’s the feeling that no one cares.\" – Unknown", category: "loneliness" },
  { text: "\"The trouble is not really in being alone, it’s being lonely. One can be lonely in the midst of a crowd.\" – Christine Feehan", category: "loneliness" },
  { text: "\"Even in the loneliest moments I’ve ever known, I’ve never been truly alone.\" – Tyler Knott Gregson", category: "loneliness" },
  { text: "\"There are worse things than feeling alone. Things like being with someone and still feeling alone.\" – M.W. Poetry", category: "loneliness" },
  { text: "\"Being alone is scarier than any boogeyman or monster under a bed.\" – Katie McGarry", category: "loneliness" },
  { text: "\"There’s nothing abnormal about loneliness.\" – Paula Stokes", category: "loneliness" },
  { text: "\"Sometimes, we just need to be heard. Not fixed, not saved—just heard.\" – Unknown", category: "loneliness" },
  { text: "\"Loneliness is an invisible wound that cuts deeper than anyone can see.\" – Unknown", category: "loneliness" },
  { text: "\"There are days when the loneliness is like a physical ache in the chest.\" – Unknown", category: "loneliness" },
  { text: "\"Loneliness is the leprosy of the modern world.\" – Mother Teresa", category: "loneliness" },
  { text: "\"I’m lonely. And I’m lonely in some horribly deep way, and for a flash of an instant, I can see just how lonely, and how deep this feeling runs.\" – Augusten Burroughs", category: "loneliness" },
  { text: "\"The most terrible poverty is loneliness, and the feeling of being unloved.\" – Mother Teresa", category: "loneliness" },
  { text: "\"Loneliness teaches us to value connection.\" – Unknown", category: "loneliness" },
  { text: "\"I restore myself when I’m alone.\" – Marilyn Monroe", category: "loneliness" },
  { text: "\"Loneliness becomes addictive once you see how peaceful it is.\" – Unknown", category: "loneliness" },
  { text: "\"Loneliness is a tax we have to pay to atone for a certain complexity of mind.\" – Alain de Botton", category: "loneliness" },
  { text: "\"In the silence of my soul, I found my voice.\" – Unknown", category: "loneliness" },
  { text: "\"Loneliness is a storm of silence that slowly erodes the heart.\" – Unknown", category: "loneliness" },
  { text: "\"Don’t feel alone, because there is always someone out there who loves you more than you know.\" – Unknown", category: "loneliness" },
  { text: "\"I felt it shelter to speak to you.\" – Emily Dickinson", category: "loneliness" },
  { text: "\"You sometimes think you want to disappear, but all you really want is to be found.\" – Unknown", category: "loneliness" },
  { text: "\"Loneliness is an emotional state in which a person experiences a powerful feeling of emptiness and isolation.\" – Unknown", category: "loneliness" },
  { text: "\"You can’t be strong all the time. Sometimes you just need someone to simply be there for you.\" – Unknown", category: "loneliness" },
  { text: "\"Aloneness is not loneliness. It’s the joy of being with oneself.\" – Osho", category: "loneliness" },
  { text: "\"Solitude gives birth to the original in us.\" – Thomas Mann", category: "loneliness" },
  { text: "\"Alone, we are strong. Together, we are stronger. But it begins with learning to stand alone.\" – Unknown", category: "loneliness" },
  { text: "\"Sometimes being surrounded by everyone is the loneliest, because you’ll realize you have no one to turn to.\" – Soraya Naomi", category: "loneliness" },
  { text: "\"When you’re surrounded by people but still feel alone, that’s when the pain really hits.\" – Unknown", category: "loneliness" },
  { text: "\"Loneliness teaches us that we are enough.\" – Unknown", category: "loneliness" },
  { text: "\"Being alone is better than being with someone who makes you feel alone.\" – Unknown", category: "loneliness" },
  { text: "\"The worst feeling is not being lonely; it’s being forgotten by someone you can’t forget.\" – Unknown", category: "loneliness" },
  { text: "\"Loneliness is not a lack of love, but a lack of connection.\" – Unknown", category: "loneliness" },
  { text: "\"Being alone doesn’t mean you’re weak. It means you’re strong enough to wait for what you deserve.\" – Unknown", category: "loneliness" },
  { text: "\"Sometimes loneliness is the price we pay for growth.\" – Unknown", category: "loneliness" },
  { text: "\"Alone time is when I distance myself from the voices of the world so I can hear my own.\" – Oprah Winfrey", category: "loneliness" },
  { text: "\"The mind is sharper and keener in seclusion and uninterrupted solitude.\" – Nikola Tesla", category: "loneliness" },
  { text: "\"Loneliness gives us room to remember who we are without the noise.\" – Unknown", category: "loneliness" },
  { text: "\"Loneliness is not cured by human company. Loneliness is cured by contact with reality.\" – Anthony de Mello", category: "loneliness" },
  { text: "\"Loneliness isn’t always the absence of people; it’s the absence of understanding.\" – Unknown", category: "loneliness" },
  { text: "\"In the silence of loneliness, your truth has a chance to speak.\" – Unknown", category: "loneliness" },
  { text: "\"There are nights when the wolves are silent and only the moon howls.\" – George Carlin", category: "loneliness" },
  { text: "\"Loneliness is the companion of wisdom.\" – Unknown", category: "loneliness" },
  { text: "\"Sometimes the most powerful thing you can do is sit in your loneliness until it tells you what it came to teach.\" – Unknown", category: "loneliness" },
  { text: "\"Even stars feel lonely in the vastness of space.\" – Unknown", category: "loneliness" },
  { text: "\"Being alone with your thoughts is a rare gift in a world of constant noise.\" – Unknown", category: "loneliness" },
  { text: "\"I have never found a companion that was so companionable as solitude.\" – Henry David Thoreau", category: "loneliness" },
  { text: "\"Loneliness is proof that your innate search for connection is still alive.\" – Martha Beck", category: "loneliness" },
  { text: "\"When we cannot bear to be alone, it means we do not properly value the only companion we will have from birth to death — ourselves.\" – Eda LeShan", category: "loneliness" },
  { text: "\"The cure for loneliness is not always company. Sometimes it’s understanding.\" – Unknown", category: "loneliness" },
  { text: "\"Solitude is where I place my chaos to rest and awaken my inner peace.\" – Nikki Rowe", category: "loneliness" },
  { text: "\"You can’t depend on anyone else, and you shouldn’t. That’s the loneliest truth of all.\" – Unknown", category: "loneliness" },
  { text: "\"Some steps need to be taken alone. It’s the only way to really figure out where you need to go and who you need to be.\" – Mandy Hale", category: "loneliness" },
  { text: "\"Loneliness is a whisper that reminds us we’re still listening for something more.\" – Unknown", category: "loneliness" },
  { text: "\"Sometimes the loudest cries for help are silent moments of isolation.\" – Unknown", category: "loneliness" },
  { text: "\"Loneliness is not the absence of affection, but the absence of understanding.\" – Beau Taplin", category: "loneliness" },
  { text: "\"In loneliness, the mind creates echoes that only the heart can hear.\" – Unknown", category: "loneliness" },
  { text: "\"Loneliness is a mirror — it shows you what you’re missing and what you’re made of.\" – Unknown", category: "loneliness" },
  { text: "\"The deepest kind of loneliness is being unseen in a world that’s always watching.\" – Unknown", category: "loneliness" },
  { text: "\"Loneliness asks hard questions, but it never lies.\" – Unknown", category: "loneliness" }
];

interface Quote {
  text: string;
  category: string;
}

function shuffleArray(array: Quote[]): Quote[] {
  // Fisher-Yates (aka Knuth) Shuffle algorithm
  const newArr = [...array];
  for (let i = newArr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [newArr[i], newArr[j]] = [newArr[j], newArr[i]];
  }
  return newArr;
}

export default function QuoteBankPage() {
  const [filter, setFilter] = useState("all");
  const navigate = useNavigate();

  // useMemo to avoid reshuffling on every render unless filter changes
  const filteredQuotes = useMemo(() => {
    const filtered = filter === "all" ? allQuotes : allQuotes.filter(q => q.category === filter);
    return shuffleArray(filtered);
  }, [filter]);

  return (
    <div className="quote-page-wrapper">
      <div className="phone-container">
        <div className="quote-bank-header">
          <div className="back-button-container">
            <button className="back-button" onClick={() => navigate("/dashboard")}>
              ← Back
            </button>
          </div>
          <h1>Quote Bank</h1>
        </div>

        <div className="sort-controls">
          <label htmlFor="sort-select">Sort by:</label>
          <select
            id="sort-select"
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
          >
            <option value="all">All</option>
            <option value="motivation">Motivation</option>
            <option value="acceptance">Acceptance</option>
            <option value="loss">Loss</option>
            <option value="loneliness">Loneliness</option>
          </select>
        </div>

        <div className="quote-list">
          {filteredQuotes.map((q, i) => (
            <div key={i} className={`quote-card ${q.category}`}>
              {q.text}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}