export interface Quote {
	text: string;
	category: string;
}

export const allQuotes: Quote[] = [
	{ text: "\"Nobody owes you nothin’. You owe yourself.\" - Rocky Balboa", category: "motivation" },
	{ text: "\"You don't have to be special, just consistent, determined, and willing to work for it.\" - Tom Brady", category: "motivation" },
	{ text: "\"Do, or do not. There is no try.\" - Yoda", category: "motivation" },
	{ text: "\"The only way to do great work is to love what you do.\" - Steve Jobs", category: "motivation" },
	{ text: "\"Believe you can and you're halfway there.\" - Theodore Roosevelt", category: "motivation" },
	{ text: "\"Don't watch the clock; do what it does. Keep going.\" - Sam Levenson", category: "motivation" },
	{ text: "\"I like criticism. It makes you strong.\" - Lebron James", category: "motivation" },
	{ text: "\"Don’t be afraid of failure. This is the way to succeed.\" - Lebron James", category: "motivation" },
	{ text: "\"Success is not final; failure is not fatal: It is the courage to continue that counts.\" - Winston Churchill", category: "motivation" },
	{ text: "\"Keep your eyes on the stars and your feet on the ground.\" - Theodore Roosevelt", category: "motivation" },
	{ text: "\"Opportunity is missed by most people because it is dressed in overalls and looks like work.\" - Thomas Edison", category: "motivation" },
	{ text: "\"Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness.\" - Oprah Winfrey", category: "motivation" },
	{ text: "\"He who conquers himself is the mightiest warrior.\" - Confucius", category: "motivation" },
	{ text: "\"Education is the most powerful weapon which you can use to change the world.\" - Nelson Mandela", category: "motivation" },
	{ text: "\"Life is like riding a bicycle. To keep your balance, you must keep moving.\" - Albert Einstein", category: "motivation" },
	{ text: "\"Be sure you put your feet in the right place, then stand firm.\" - Abraham Lincoln", category: "motivation" },
	{ text: "\"You don’t find willpower, you create it.\" - Kobe Bryant", category: "motivation" },
	{ text: "\"Discipline is doing what needs to be done, even when you don’t feel like doing it.\" - Mike Tyson", category: "motivation" },
	{ text: "\"Hard work beats talent when talent doesn’t work hard.\" - Tim Notke", category: "motivation" },
	{ text: "\"If you want to be great, stop asking for permission.\" - Ray Lewis", category: "motivation" },
	{ text: "\"Champions keep playing until they get it right.\" - Billie Jean King", category: "motivation" },
	{ text: "\"The pain you feel today will be the strength you feel tomorrow.\" - Arnold Schwarzenegger", category: "motivation" },
	{ text: "\"You have to expect things of yourself before you can do them.\" - Michael Jordan", category: "motivation" },
	{ text: "\"No one is going to hand you anything. You have to go out and take it.\" - Derrick Rose", category: "motivation" },
	{ text: "\"Success doesn’t come from what you do occasionally, it comes from what you do consistently.\" - Marie Forleo", category: "motivation" },
	{ text: "\"It’s not about being the best. It’s about being better than you were yesterday.\" - J.J. Watt", category: "motivation" },
	{ text: "\"Never let the fear of striking out keep you from playing the game.\" - Babe Ruth", category: "motivation" },
	{ text: "\"Pressure is a privilege.\" - Billie Jean King", category: "motivation" },
	{ text: "\"Don’t count the days, make the days count.\" - Muhammad Ali", category: "motivation" },
	{ text: "\"Some people want it to happen, some wish it would happen, others make it happen.\" - Michael Jordan", category: "motivation" },
	{ text: "\"Excellence is not a singular act, but a habit. You are what you repeatedly do.\" - Shaquille O’Neal", category: "motivation" },
	{ text: "\"Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing.\" - Pelé", category: "motivation" },
	{ text: "\"Every champion was once a contender that refused to give up.\" - Rocky Balboa", category: "motivation" },
	{ text: "\"The difference between the impossible and the possible lies in a person’s determination.\" - Tommy Lasorda", category: "motivation" },
	{ text: "\"It’s not whether you get knocked down, it’s whether you get up.\" - Vince Lombardi", category: "motivation" },
	{ text: "\"The only place success comes before work is in the dictionary.\" - Vince Lombardi", category: "motivation" },
	{ text: "\"Winning takes talent, to repeat takes character.\" - John Wooden", category: "motivation" },
	{ text: "\"Don’t measure yourself by what you have accomplished, but by what you should have accomplished with your ability.\" - John Wooden", category: "motivation" },
	{ text: "\"I’ve failed over and over and over again in my life. And that is why I succeed.\" - Michael Jordan", category: "motivation" },
	{ text: "\"Greatness is not guarding yourself from the people; greatness is being accepted by the people.\" - Mike Tyson", category: "motivation" },
	{ text: "\"When you’re good at something, you’ll tell everyone. When you’re great at something, they’ll tell you.\" - Walter Payton", category: "motivation" },
	{ text: "\"I hated every minute of training, but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion.’\" - Muhammad Ali", category: "motivation" },
	{ text: "\"Push yourself again and again. Don’t give an inch until the final buzzer sounds.\" - Larry Bird", category: "motivation" },
	{ text: "\"Success is achieved by developing our strengths, not by eliminating our weaknesses.\" - Marilyn vos Savant", category: "motivation" },
	{ text: "\"There may be people that have more talent than you, but there’s no excuse for anyone to work harder than you do.\" - Derek Jeter", category: "motivation" },
	{ text: "\"Confidence comes from preparation. Everything else is beyond your control.\" - Peyton Manning", category: "motivation" },
	{ text: "\"Do not let what you cannot do interfere with what you can do.\" - John Wooden", category: "motivation" },
	{ text: "\"Always turn a negative situation into a positive one.\" - Michael Jordan", category: "motivation" },
	{ text: "\"Talent is God-given. Be humble. Fame is man-given. Be grateful. Conceit is self-given. Be careful.\" - John Wooden", category: "motivation" },
	{ text: "\"Success usually comes to those who are too busy to be looking for it.\" - Henry David Thoreau", category: "motivation" },
	{ text: "\"Strive not to be a success, but rather to be of value.\" - Albert Einstein", category: "motivation" },
	{ text: "\"Whether you think you can or you think you can’t, you’re right.\" - Henry Ford", category: "motivation" },
	{ text: "\"If you’re going through hell, keep going.\" - Winston Churchill", category: "motivation" },
	{ text: "\"Act as if what you do makes a difference. It does.\" - William James", category: "motivation" },
	{ text: "\"Success is getting what you want. Happiness is wanting what you get.\" - Dale Carnegie", category: "motivation" },
	{ text: "\"Don’t wait. The time will never be just right.\" - Napoleon Hill", category: "motivation" },
	{ text: "\"It does not matter how slowly you go as long as you do not stop.\" - Confucius", category: "motivation" },
	{ text: "\"You have power over your mind—not outside events. Realize this, and you will find strength.\" - Marcus Aurelius", category: "motivation" },
	{ text: "\"Be yourself; everyone else is already taken.\" - Oscar Wilde", category: "motivation" },
	{ text: "\"If you want to lift yourself up, lift up someone else.\" - Booker T. Washington", category: "motivation" },
	{ text: "\"The best way to predict the future is to create it.\" - Peter Drucker", category: "motivation" },
	{ text: "\"The only limit to our realization of tomorrow is our doubts of today.\" - Franklin D. Roosevelt", category: "motivation" },
	{ text: "\"What lies behind us and what lies before us are tiny matters compared to what lies within us.\" - Ralph Waldo Emerson", category: "motivation" },
	{ text: "\"I am not a product of my circumstances. I am a product of my decisions.\" - Stephen Covey", category: "motivation" },
	{ text: "\"The future belongs to those who believe in the beauty of their dreams.\" - Eleanor Roosevelt", category: "motivation" },
	{ text: "\"Start where you are. Use what you have. Do what you can.\" - Arthur Ashe", category: "motivation" },
	{ text: "\"Do one thing every day that scares you.\" - Eleanor Roosevelt", category: "motivation" },
	{ text: "\"Success is liking yourself, liking what you do, and liking how you do it.\" - Maya Angelou", category: "motivation" },
	{ text: "\"The way to get started is to quit talking and begin doing.\" - Walt Disney", category: "motivation" },
	{ text: "\"Dream big and dare to fail.\" - Norman Vaughan", category: "motivation" },
	{ text: "\"Success is how high you bounce when you hit bottom.\" - George S. Patton", category: "motivation" },
	{ text: "\"Energy and persistence conquer all things.\" - Benjamin Franklin", category: "motivation" },
	{ text: "\"Work like hell. I mean you just have to put in 80 to 100 hour weeks every week.\" - Elon Musk", category: "motivation" },
	{ text: "\"If something is important enough, even if the odds are against you, you should still do it.\" - Elon Musk", category: "motivation" },
	{ text: "\"Innovation distinguishes between a leader and a follower.\" - Steve Jobs", category: "motivation" },
	{ text: "\"Stay hungry. Stay foolish.\" - Steve Jobs", category: "motivation" },
	{ text: "\"Your time is limited, so don’t waste it living someone else’s life.\" - Steve Jobs", category: "motivation" },
	{ text: "\"Logic will get you from A to B. Imagination will take you everywhere.\" - Albert Einstein", category: "motivation" },
	{ text: "\"It always seems impossible until it’s done.\" - Nelson Mandela", category: "motivation" },
	{ text: "\"We must use time wisely and forever realize that the time is always ripe to do right.\" - Nelson Mandela", category: "motivation" },
	{ text: "\"What you do makes a difference, and you have to decide what kind of difference you want to make.\" - Jane Goodall", category: "motivation" },
	{ text: "\"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.\" - Christian D. Larson", category: "motivation" },
	{ text: "\"Success is the sum of small efforts, repeated day in and day out.\" - Robert Collier", category: "motivation" },
	{ text: "\"What you get by achieving your goals is not as important as what you become by achieving your goals.\" - Zig Ziglar", category: "motivation" },
	{ text: "\"Perseverance is not a long race; it is many short races one after another.\" - Walter Elliot", category: "motivation" },
	{ text: "\"Limit your ‘always’ and your ‘nevers.’\" - Amy Poehler", category: "motivation" },
	{ text: "\"Success is not how high you have climbed, but how you make a positive difference to the world.\" - Roy T. Bennett", category: "motivation" },
	{ text: "\"Opportunity is everywhere. The key is to develop the vision to see it.\" - Robin Sharma", category: "motivation" },
	{ text: "\"You can't cross the sea merely by standing and staring at the water.\" - Rabindranath Tagore", category: "motivation" },
	{ text: "\"If opportunity doesn’t knock, build a door.\" - Milton Berle", category: "motivation" },
	{ text: "\"Don’t limit yourself. Many people limit themselves to what they think they can do.\" - Mary Kay Ash", category: "motivation" },
	{ text: "\"Be so good they can’t ignore you.\" - Steve Martin", category: "motivation" },
	{ text: "\"The most difficult thing is the decision to act, the rest is merely tenacity.\" - Amelia Earhart", category: "motivation" },
	{ text: "\"You miss 100% of the shots you don’t take.\" - Wayne Gretzky", category: "motivation" },
	{ text: "\"Do not go where the path may lead, go instead where there is no path and leave a trail.\" - Ralph Waldo Emerson", category: "motivation" },
	{ text: "\"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.\" - Roy T. Bennett", category: "motivation" },
	{ text: "\"Only those who dare to fail greatly can ever achieve greatly.\" - Robert F. Kennedy", category: "motivation" },
	{ text: "\"Success means doing the best we can with what we have.\" - Zig Ziglar", category: "motivation" },
	{ text: "\"Never bend your head. Always hold it high. Look the world straight in the eye.\" - Helen Keller", category: "motivation" },
	{ text: "\"If you want something you've never had, you must be willing to do something you've never done.\" - Thomas Jefferson", category: "motivation" },
	{ text: "\"No one ever told me that grief felt so like fear.\" - C.S. Lewis", category: "loss" },
	{ text: "\"The reality is that you will grieve forever. You will not ‘get over’ the loss of a loved one; you will learn to live with it.\" - Elisabeth Kubler-Ross", category: "loss" },
	{ text: "\"You may not control all the events that happen to you, but you can decide not to be reduced by them.\" - Maya Angelou", category: "loss" },
	{ text: "\"You will lose someone you can’t live without, and your heart will be badly broken... But the truth is that grief is like the ocean; it comes on waves, ebbing and flowing.\" - Anne Lamott", category: "loss" },
	{ text: "\"The deeper that sorrow carves into your being, the more joy you can contain.\" - Khalil Gibran", category: "loss" },
	{ text: "\"Grief turns out to be a place none of us know until we reach it.\" - Joan Didion", category: "loss" },
	{ text: "\"Grief is the price we pay for love.\" - Queen Elizabeth II", category: "loss" },
	{ text: "\"Grief and resilience live together.\" - Michelle Obama", category: "loss" },
	{ text: "\"The pain of loss is a reminder that we have loved deeply. And the depth of that love can inspire us to be better, kinder, more courageous people.\" - Barack Obama", category: "loss" },
	{ text: "\"Anything that's human is mentionable, and anything that is mentionable can be more manageable.\" - Mr. Rogers", category: "loss" },
	{ text: "\"Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.\" - Steve Jobs", category: "loss" },
	{ text: "\"Only when we are brave enough to explore the darkness will we discover the infinite power of our light.\" - Brene Brown", category: "loss" },
	{ text: "\"The greatest glory in living lies not in never falling, but in rising every time we fall.\" - Nelson Mandela", category: "loss" },
	{ text: "\"You never know how strong you are until being strong is your only choice.\" - Bob Marley", category: "loss" },
	{ text: "\"Turn your wounds into wisdom.\" - Oprah Winfrey", category: "loss" },
	{ text: "\"We must accept finite disappointment, but never lose infinite hope.\" - Martin Luther King Jr.", category: "loss" },
	{ text: "\"What we have once enjoyed we can never lose. All that we love deeply becomes a part of us.\" - Helen Keller", category: "loss" },
	{ text: "\"The best way to not feel hopeless is to get up and do something.\" - Barack Obama", category: "loss" },
	{ text: "\"When we are no longer able to change a situation, we are challenged to change ourselves.\" - Viktor Frankl", category: "loss" },
	{ text: "\"Helping people in need is a good and essential part of my life, a kind of destiny.\" - Princess Diana", category: "loss" },
	{ text: "\"The world breaks everyone, and afterward, many are strong at the broken places.\" - Ernest Hemingway", category: "loss" },
	{ text: "\"If you’re going through hell, keep going.\" - Winston Churchill", category: "loss" },
	{ text: "\"Don’t grieve. Anything you lose comes round in another form.\" - Rumi", category: "loss" },
	{ text: "\"Our greatest glory is not in never falling, but in rising every time we fall.\" - Confucius", category: "loss" },
	{ text: "\"There is a crack in everything, that’s how the light gets in.\" - Leonard Cohen", category: "loss" },
	{ text: "\"Tears shed for another person are not a sign of weakness. They are a sign of a pure heart.\" - José N. Harris", category: "loss" },
	{ text: "\"Sadness flies away on the wings of time.\" - Jean de La Fontaine", category: "loss" },
	{ text: "\"Grief is in two parts. The first is loss. The second is the remaking of life.\" - Anne Roiphe", category: "loss" },
	{ text: "\"How lucky I am to have something that makes saying goodbye so hard.\" - A.A. Milne", category: "loss" },
	{ text: "\"To weep is to make less the depth of grief.\" - William Shakespeare", category: "loss" },
	{ text: "\"Sometimes even to live is an act of courage.\" - Seneca", category: "loss" },
	{ text: "\"Out of suffering have emerged the strongest souls.\" - Khalil Gibran", category: "loss" },
	{ text: "\"Do not cry because they are gone. Smile because they lived.\" - Dr. Seuss", category: "loss" },
	{ text: "\"Healing doesn’t mean the damage never existed. It means the damage no longer controls our lives.\" - Akshay Dubey", category: "loss" },
	{ text: "\"Grief does not change you. It reveals you.\" - John Green", category: "loss" },
	{ text: "\"You cannot protect yourself from sadness without protecting yourself from happiness.\" - Jonathan Safran Foer", category: "loss" },
	{ text: "\"There is something beautiful about all scars, whatever nature. A scar means the hurt is over.\" - Harry Crews", category: "loss" },
	{ text: "\"Hope is being able to see that there is light despite all of the darkness.\" - Desmond Tutu", category: "loss" },
	{ text: "\"Every man's memory is his private literature.\" - Aldous Huxley", category: "loss" },
	{ text: "\"We bereaved are not alone. We belong to the largest company in all the world—the company of those who have known suffering.\" - Helen Keller", category: "loss" },
	{ text: "\"The pain passes, but the beauty remains.\" - Pierre Auguste Renoir", category: "loss" },
	{ text: "\"Loss is nothing else but change, and change is Nature’s delight.\" - Marcus Aurelius", category: "loss" },
	{ text: "\"Give sorrow words; the grief that does not speak knits up the o’er-wrought heart and bids it break.\" - William Shakespeare", category: "loss" },
	{ text: "\"When someone you love becomes a memory, that memory becomes a treasure.\" - Lebron Al-Jameel", category: "loss" },
	{ text: "\"The song is ended, but the melody lingers on.\" - Irving Berlin", category: "loss" },
	{ text: "\"Grief is love with nowhere to go.\" - Jamie Anderson", category: "loss" },
	{ text: "\"Life is full of grief, to exactly the degree we allow ourselves to love other people.\" - Orson Scott Card", category: "loss" },
	{ text: "\"People touch our lives if only for a moment, and yet we’re not the same from that moment on.\" - Lebron Al-Jameel", category: "loss" },
	{ text: "\"Death ends a life, not a relationship.\" - Mitch Albom", category: "loss" },
	{ text: "\"Nothing that grieves us can be called little; by the eternal laws of proportion a child’s loss of a doll and a king’s loss of a crown are events of the same size.\" - Mark Twain", category: "loss" },
	{ text: "\"To live in hearts we leave behind is not to die.\" - Thomas Campbell", category: "loss" },
	{ text: "\"Sometimes the smallest things take up the most room in your heart.\" - A.A. Milne", category: "loss" },
	{ text: "\"Say not in grief ‘he is no more,’ but live in thankfulness that he was.\" - Hebrew Proverb", category: "loss" },
	{ text: "\"When we lose someone we love, we must learn not to live without them, but to live with the love they left behind.\" - Lebron Al-Jameel", category: "loss" },
	{ text: "\"Death leaves a heartache no one can heal, love leaves a memory no one can steal.\" - Irish Proverb", category: "loss" },
	{ text: "\"The reality is that you will grieve forever. You will not ‘get over’ the loss... you will be healed and you will rebuild yourself around the loss you have suffered.\" - Lebron Al-Jameel", category: "loss" },
	{ text: "\"Grief is not a disorder, a disease or a sign of weakness. It is an emotional, physical and spiritual necessity.\" - Earl Grollman", category: "loss" },
	{ text: "\"Sometimes we just need someone to simply be there — not to fix anything, but to let us feel we are supported and not alone.\" - Lebron Al-Jameel", category: "loss" },
	{ text: "\"Those we love and lose are always connected by heartstrings into infinity.\" - Terri Guillemets", category: "loss" },
	{ text: "\"Say goodbye to the past, but never forget it — it made you who you are.\" - Lebron Al-Jameel", category: "loss" },
	{ text: "\"You don’t get over it, you just get through it. You don’t get by it, because you can’t get around it. It doesn’t ‘get better,’ it just gets different.\" - Lebron Al-Jameel", category: "loss" },
	{ text: "\"You’ll get through this. It will hurt, but you’ll come out stronger on the other side. Different, but stronger.\" - Lebron Al-Jameel", category: "loss" },
	{ text: "\"Sometimes grief is like a raging river; other times, it's a quiet ache. But it is always love trying to find a place to land.\" - Lebron Al-Jameel", category: "loss" },
	{ text: "\"No rule book. No time frame. No judgment. Grieve how you need to.\" - Lebron Al-Jameel", category: "loss" },
	{ text: "\"There is no right way to grieve; there is only your way.\" - Lebron Al-Jameel", category: "loss" },
	{ text: "\"Each person's grief is as unique as their fingerprint.\" - Lebron Al-Jameel", category: "loss" },
	{ text: "\"Time does not heal everything but acceptance will heal everything.\" - Lebron Al-Jameel", category: "acceptance" },
	{ text: "\"Every day is a new beginning. Take a deep breath, smile, and start again.\" - Lebron Al-Jameel", category: "acceptance" },
	{ text: "\"Sometimes you need to be alone. Not to be lonely, but to enjoy your free time being yourself.\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"Sometimes I just want someone to hug me and say, ‘I know it’s hard. You’re going to be okay.’\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"Loneliness doesn’t come from being alone. It comes from feeling like no one cares.\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"Sometimes, you just need a break. In a beautiful place. Alone. To figure everything out.\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"You sometimes think you want to disappear, but all you really want is to be found.\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"You can’t be strong all the time. Sometimes you just need someone to simply be there for you.\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"Being alone is better than being with someone who makes you feel alone.\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"The worst feeling is not being lonely; it’s being forgotten by someone you can’t forget.\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"Being alone doesn’t mean you’re weak. It means you’re strong enough to wait for what you deserve.\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"Sometimes loneliness is the price we pay for growth.\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"Loneliness gives us room to remember who we are without the noise.\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"Loneliness isn’t always the absence of people; it’s the absence of understanding.\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"Loneliness is a mirror — it shows you what you’re missing and what you’re made of.\" - Lebron Al-Jameel", category: "loneliness" },
	{ text: "\"Loneliness asks hard questions, but it never lies.\" - Lebron Al-Jameel", category: "loneliness" }
];

export function getCategoryFromQuote(quote: string): string | null {
	const foundQuote = allQuotes.find(q => q.text === quote);
	
	return foundQuote ? foundQuote.category : null;
}